### PR TITLE
bug(#9): refactored, simplified `MjSodg` and related classes

### LINKED ISSUE #9: SodgFiles.java:35-38: Refactor {@link SodgFiles} class to...
The puzzle `1-f28c8a93` from #1 has to be resolved: 

https://github.com/objectionary/sodg-maven-plugin/blob/1c68695059e84c3396268ed84198208298fd0daf/src/main/java/org/eolang/sodg/SodgFiles.java#L35-L38

The puzzle was created by @volodya-lombrozo on 01-Apr-25. 

Estimate: 90 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

### PR DESCRIPTION
**Pull request by h1alexbel**
In this PR I've refactored `org.eolang.sodg.MjSodg` and related classes, to get rid of high complexity, reported by Checkstyle and PMD.

closes #9

### CODE REVIEW

**Comment by h1alexbel** [comment]
@volodya-lombrozo could you take a look, please?

File: src/main/java/org/eolang/sodg/Depo.java [hunk 1]
```diff
@@ -0,0 +1,22 @@
...
+package org.eolang.sodg;
+
+import com.yegor256.xsline.Shift;
+import com.yegor256.xsline.Train;
+
+/**
+ * Train depo.
+ * @since 0.0.3
+ */
+interface Depo {
```
Comment (volodya-lombrozo) [inline src/main/java/org/eolang/sodg/Depo.java:14]: @h1alexbel there is no such thing as "depo" in eng. Did you mean [depot](https://dictionary.cambridge.org/dictionary/english/depot)? Some javadocs would greatly help understand the purpose of this abstraction.

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]
@h1alexbel Great, thanks for the PR! It has significant value. However, there are too many changes in a single PR:

["Helping others review your changes"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/helping-others-review-your-changes#write-small-pull-requests):

> [Write small pull requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/getting-started/helping-others-review-your-changes#write-small-pull-requests)
Aim to create small, focused pull requests that fulfill a single purpose. Smaller pull requests are easier and faster to review and merge, leave less room to introduce bugs, and provide a clearer history of changes.

Thus, I suggest reducing the number of changes.
In addition, this repository lacks tests, which makes refactoring a bit harder, as we can’t be confident that we haven’t broken anything during the process. It might make sense to add unit tests for all the new classes we introduce.

**Review by volodya-lombrozo — CHANGES_REQUESTED** [review]
@h1alexbel Thanks! It's better. I have left several suggestions. Could you take a look, please

**Comment by h1alexbel** [comment]
@volodya-lombrozo updated. Take a look, please

**Comment by volodya-lombrozo** [comment]
@yegor256 can we merge this one, please?

**Comment by yegor256** [comment]
@h1alexbel thanks!
